pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Crear entorrno virtual y activar ') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install ansible
                ansible -i ansible/inventory.ini webserver -m ping
                '''
            }
        }

        stage('Ejecutar playbook'){
            steps {
                sh '''
                ansible-playbook -i ansible/inventory.ini ansible/playbook.yaml
                '''
            }
        }
}

    post {
        always {
            cleanWs() // Limpieza final automática con el plugin Workspace Cleanup
        }
        success {
            echo '✅ Playbook ejecutado correctamente.'
        }
        failure {
            echo '❌ Error al ejecutar el playbook.'
        }
    }
}