pipeline {
    agent any

    environment {
        ANSIBLE_HOST_KEY_CHECKING = 'False'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Crear entorrno virtual y activar ') {
            steps {
                sh '''
                python3 -m venv env-devops
                '''
            }
        }

        stage('Activar entorno virtual') {
            steps {
                sh '''
                source /var/lib/jenkins/workspace/pipeline-ansible/env-devops/bin/activate
                '''
            }
        }

        stage('instalar ansible') {
            steps {
                sh '''
                pip install ansible -y
                '''
            }
        }

        stage('validar conexión a servidores ') {
            steps {
                sh '''
                ansible all -i inventory.ini webserver -m ping
                '''
            }
        }
    }

    post {
        always {
            cleanWs() // Limpieza final automática con el plugin Workspace Cleanup
        }
        success {
            echo '✅ Playbook ejecutado correctamente.'
        }
        failure {
            echo '❌ Error al ejecutar el playbook.'
        }
    }
}